New Pull Request
APC524-F2023/Endpoint-conditioned-Markov-continuous-chains-on-a-finite-state-space pull request #8
Opened 2023-11-17 00:07 UTC by Chenxiao-Tian

2023-11-17 00:16 UTC, Chenxiao-Tian reviewed
CI Testing

2023-11-17 00:42 UTC, jyl17 requested changes
I think the commits should be merged into main (not other branches)

2023-11-17 00:42 UTC, jyl17 commented on ci.yml
It'll be good to combine the file with the existing one in .github/workflows

2023-11-17 00:42 UTC, jyl17 commented on test_sampling.py
> +import pytest
```suggestion
```

2023-11-17 00:42 UTC, jyl17 commented on test_sampling.py
Can be moved to the tests folder

2023-11-17 00:42 UTC, jyl17 commented on tests/ci.yml
Should be moved to .github/workflows,  combining with the existing ci.yml in that folder

2023-11-17 00:42 UTC, jyl17 commented on tests/test_sampling.py
> +import pytest
```suggestion
```

2023-11-17 00:42 UTC, jyl17 commented on tests/test_sampling.py
> +from your_script_name import direct_sampling_with_times  # Replace with your actual script name
Might need some packaging to get rid of this

2023-11-17 00:42 UTC, jyl17 commented on git
Can be removed

2023-11-17 17:43 UTC, jyl17 reviewed
might be good to merge this ci.yml file with the existing one

2023-11-17 17:43 UTC, jyl17 commented on tests/ci.yml
> +        pytest
```suggestion
```

2023-11-17 17:43 UTC, jyl17 commented on tests/ci.yml
> +      run: |
```suggestion
      run: python -m pytest
```

2023-11-17 17:43 UTC, jyl17 commented on tests/ci.yml
> +        pip install numpy pytest  # Add any other dependencies
```suggestion
        pip install -e .[test]  # test is defined in pyproject.toml and contain all dependencies
```

2023-11-19 20:07 UTC, jyl17 reviewed
need package for test to pass successful

2023-11-19 20:07 UTC, jyl17 commented on tests/test_sampling.py
> +from your_script_name import direct_sampling_with_times  # Replace with your actual script name
```suggestion
import ECMC
```

2023-11-19 23:29 UTC, merged

2023-11-20 04:26 UTC, Xuyang-Xu commented on tests/ci.yml
> +on: [push, pull_request]
should be changed to
on:
  pull_request:
  push:
    branches:
      - main